/* K — Espada. A separate design experiment with local practice history. */
const kTopics=[{id:'fractions',grade:6,title:'Обыкновенные дроби',short:'Дроби',image:'topic-fractions.jpg',intro:'Поймём, как делить целое на равные части и узнавать одинаковые дроби.'},{id:'numbers',grade:5,title:'Числа и порядок действий',short:'Числа',image:'topic-numbers.jpg',intro:'Разберём разряды, скобки и порядок действий на понятных примерах.'},{id:'geometry',grade:5,title:'Периметр и площадь',short:'Фигуры',image:'topic-geometry.jpg',intro:'Научимся отличать длину границы от места внутри фигуры.'}];
const kExtra={equations:[{title:'Найди x: x + 7 = 12',answers:['5','19','7'],correct:0,hint:'Вычти 7 из обеих частей равенства.',explanation:'12 − 7 = 5. Проверка: 5 + 7 = 12.'},{title:'Найди x: 3 × x = 18',answers:['15','6','21'],correct:1,hint:'Раздели обе части на 3.',explanation:'18 ÷ 3 = 6. Проверка: 3 × 6 = 18.'},{title:'Найди x: x − 4 = 9',answers:['5','36','13'],correct:2,hint:'Прибавь 4 к обеим частям.',explanation:'9 + 4 = 13. Проверка: 13 − 4 = 9.'}],chance:[{title:'В мешке 3 зелёных и 1 белый шар. Какова вероятность достать белый?',answers:[['1','4'],['3','4'],['1','3']],correct:0,hint:'Всего четыре одинаково вероятных шара, белый только один.',explanation:'Один подходящий исход из четырёх: вероятность 1/4.'},{title:'Какова вероятность получить чётное число на обычном кубике?',answers:[['1','6'],['1','2'],['2','3']],correct:1,hint:'Чётные грани: 2, 4 и 6. Всего граней шесть.',explanation:'Три чётных числа из шести: 3/6 = 1/2.'},{title:'В коробке только зелёные карандаши. Какова вероятность взять зелёный?',answers:['0','1/2','1'],correct:2,hint:'Любой карандаш в коробке зелёный.',explanation:'Это достоверное событие. Его вероятность равна 1.'}]};
let kGrade=5,kHistory={},kRead={},kSession=null,kReady=null,kMode='overview',kSummary=null,kSaveFailed=false;
try{const s=JSON.parse(localStorage.getItem('espada-k-progress-v1')||'{}');if([5,6,7,8,9,10,11].includes(s.grade))kGrade=s.grade;for(const [key,v] of Object.entries(s.history||{})){if(/^(fractions|numbers|geometry|equations|chance):[0-2]$/.test(key)&&v&&typeof v.correct==='boolean'&&Number.isInteger(v.choice)&&v.choice>=0&&v.choice<3)kHistory[key]={correct:v.correct,choice:v.choice,earned:v.earned===true};}for(const id of ['fractions','numbers','geometry'])if(s.read?.[id]===true)kRead[id]=true;}catch{}
function kSave(){try{localStorage.setItem('espada-k-progress-v1',JSON.stringify({grade:kGrade,history:kHistory,read:kRead}));kSaveFailed=false}catch{kSaveFailed=true}}
function kReset(){kHistory={};kRead={};kSession=null;kReady=null;kSummary=null;kSave()}
function kBank(id){return id==='fractions'?clarityFractionQuestions:id==='numbers'?banks[1]:id==='geometry'?banks[2]:kExtra[id]||[]}
function kGet(key){const [id,n]=key.split(':');return kBank(id)[Number(n)]}
function kQuestion(){return kGet(kSession.keys[kSession.position])}
function kKeys(id){return kBank(id).map((_,i)=>id+':'+i)}
function kErrors(){return Object.keys(kHistory).filter(key=>!kHistory[key].correct)}
function kXP(){return Object.values(kHistory).filter(v=>v.earned).length*20}
function kPlural(n){return n%10===1&&n%100!==11?'задание':n%10>=2&&n%10<=4&&(n%100<12||n%100>14)?'задания':'заданий'}
function kTitle(id){return ({fractions:'Дроби',numbers:'Вычисления',geometry:'Геометрия',equations:'Уравнения',chance:'Данные и шанс'})[id]}
function kAsset(name,cls=''){return `<img class="k-asset ${cls}" src="assets/espada-${name}.png" alt="" width="96" height="96">`}
function kBtn(label,action,secondary=false){return `<button class="k-button ${secondary?'k-secondary':''}" data-k="${action}">${label}</button>`}
function kNav(){return `<nav class="k-nav" aria-label="Главное меню">${[['today','Курс по классам','course'],['training','Тренировка','training'],['progress','Мой прогресс','progress']].map(([id,label,img])=>`<button data-k-nav="${id}" aria-label="${label}" title="${label}" ${screen===id||id==='today'&&screen==='learn'?'aria-current="page"':''}>${kAsset(img)}<span class="k-nav-dot"></span></button>`).join('')}</nav>`}
function kBrand(){return `<button class="k-brand" data-k-nav="today" aria-label="Espada — главная"><img src="assets/knight-${dark?'dark':'light'}.jpg" alt=""><span>espada.</span></button>`}
function kShell(content,animate){const focus=screen==='lesson'||screen==='practice';return `<div class="k-shell ${focus?'k-focus':''}">${focus?`<header class="k-focus-header"><button class="k-back" data-k="exit" aria-label="Вернуться назад">${clarityIcon('back')}</button>${kBrand()}<span class="k-focus-caption">${screen==='lesson'?kTopics[topicIndex].short:kSession?.title||'Тренировка'}</span><div class="k-tools">${clarityThemeButton()}${clarityTools()}</div></header>`:`<aside class="k-sidebar">${kBrand()}${kNav()}<div class="k-sidebar-bottom"><span class="k-side-note">Маленькие шаги.<br>Большие открытия.</span><div class="k-tools">${clarityThemeButton()}${clarityTools()}</div></div></aside><header class="k-mobile-head">${kBrand()}<div class="k-tools">${clarityThemeButton()}${clarityTools()}</div></header>`}<div class="k-workspace"><main class="k-main ${animate?'scene':''}">${content}</main>${focus?'':kRail()}</div></div>`}
function kRail(){return `<aside class="k-rail"><div class="k-profile"><span>А</span><div><strong>Алексей</strong><small>Твой путь в математике</small></div></div><section class="k-card k-points">${kAsset('progress')}<span class="k-eyebrow">ТВОИ ОТКРЫТИЯ</span><h2>${kXP()} <small>очков</small></h2><p>${kXP()<100?'Ещё '+(100-kXP())+' до Исследователя':kXP()<300?'Исследователь · ещё '+(300-kXP())+' до Знатока':'Уровень «Знаток»'}</p><div class="k-meter"><i style="width:${kXP()<100?kXP():kXP()<300?(kXP()-100)/2:100}%"></i></div></section><button class="k-radar-peek" data-k-nav="progress">${clarityMiniRadar()}<strong>Карта знаний</strong><span>Посмотри, что уже получается</span></button><section class="k-rail-note"><span>Не нужно всё сразу.</span><p>Один понятный шаг сегодня — уже хороший результат.</p></section><small class="k-storage-note">${kSaveFailed?'Браузер не сохранил прогресс. Он доступен до перезагрузки.':'Учебный прототип. Ответы сохраняются в этом браузере.'}</small></aside>`}
function kCourse(){const selected=kTopics.map((t,i)=>({...t,i})).filter(t=>t.grade===kGrade);return `<header class="k-page-heading"><span class="k-eyebrow">МАТЕМАТИКА · ТВОЙ ТЕМП</span><h1>Каждый шаг — открытие.</h1><p>Выбери класс. Найди тему. Разберись по-своему.</p></header><div class="k-grade-row"><span>Мой класс</span><div role="group" aria-label="Выбор класса">${[5,6,7,8,9,10,11].map(g=>`<button data-k-grade="${g}" aria-pressed="${kGrade===g}">${g}<span class="sr-only"> класс</span></button>`).join('')}</div></div>${selected.length?`<section class="k-course-intro"><div><span class="k-eyebrow">${kGrade} КЛАСС</span><h2>${kGrade===5?'Собираем основу':'Находим связи'}</h2><p>В каждом уроке — видео, понятное объяснение и практика.</p></div>${kAsset('course')}</section><div class="k-course-path">${selected.map((t,n)=>kCourseCard(t,n)).join('')}</div>`:`<section class="k-card k-soon"><span class="k-eyebrow">${kGrade} КЛАСС</span><h2>Что будем изучать</h2><p>Программа из Espada. Для интерактивного просмотра сейчас открыты уроки 5 и 6 классов.</p><ul>${kCatalog.filter(t=>t.grade===kGrade).map(t=>`<li>${t.title}</li>`).join('')}</ul>${kBtn('Открыть уроки 5 класса','grade-five',true)}</section>`}<p class="k-footnote">Можно начинать с любой темы. Мы подстроимся под твой темп.</p>`}
function kCourseCard(t,n){const total=kKeys(t.id).filter(k=>kHistory[k]?.correct).length,started=kKeys(t.id).some(k=>kHistory[k]),read=kRead[t.id];return `<article class="k-course-stop"><span class="k-stop-number" aria-hidden="true">${total===3?'✓':String(n+1).padStart(2,'0')}</span><button class="k-topic" data-k-topic="${t.i}"><div class="k-topic-copy"><span class="k-eyebrow">${t.grade} КЛАСС · ${total===3?'ПОЛУЧИЛОСЬ!':started?'ПРОДОЛЖИМ':'НОВОЕ ОТКРЫТИЕ'}</span><h2>${t.title}</h2><p>${t.intro}</p><div class="k-topic-meta"><span>▷ Видео</span><span>${read?'✓':'▤'} Объяснение</span><span>${total}/3 верно</span></div><strong class="k-topic-cta">${started?'Продолжить':'Открыть урок'} ${clarityIcon('arrow')}</strong></div><img class="k-topic-cover" src="assets/${t.image}" alt=""></button></article>`}
function kOpenLesson(i){topicIndex=i;kMode='overview';kReady=null;go('lesson')}
function kLesson(){const t=kTopics[topicIndex],v=kVideos[topicIndex];const tabs=`<nav class="k-lesson-tabs" aria-label="Материалы урока">${[['overview','Обзор'],['video','Видеоурок'],['read','Объяснение']].map(([id,label])=>`<button data-k-mode="${id}" aria-current="${kMode===id?'page':'false'}">${label}</button>`).join('')}</nav>`;if(kMode==='read')return tabs+clarityLesson();if(kMode==='video')return tabs+`<header class="k-page-heading"><span class="k-eyebrow">ВИДЕОУРОК · ${v.duration}</span><h1>${v.title}</h1><p>Можно остановиться, пересмотреть или перейти к объяснению.</p></header><div class="k-video-player"><iframe title="Видеоурок: ${v.title}" src="https://www.youtube-nocookie.com/embed/${v.id}?playsinline=1&rel=0&hl=ru&autoplay=0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture; fullscreen" allowfullscreen referrerpolicy="strict-origin-when-cross-origin"></iframe></div><p class="k-video-source">Видео из подборки Espada · ${v.sourceGrade} класс в исходном плейлисте.</p><a class="k-video-link" href="https://www.youtube.com/watch?v=${v.id}" target="_blank" rel="noopener">Открыть видео на YouTube ↗</a><div class="k-next-options">${kBtn('К объяснению','read')}${kBtn('Попробовать 3 задания','lesson-practice',true)}</div>`;
return `<header class="k-lesson-hero"><div><span class="k-eyebrow">${t.grade} КЛАСС · МАТЕМАТИКА</span><h1>${t.title}</h1><p>${t.intro}</p><span class="k-lesson-pill">В твоём темпе · без таймера</span></div><img src="assets/${t.image}" alt=""></header>${tabs}<section class="k-video-card"><button data-k-mode="video" class="k-video-poster" aria-label="Смотреть видео: ${v.title}"><img src="assets/${t.image}" alt=""><span class="k-play">▶</span><span class="k-duration">${v.duration}</span></button><div><span class="k-eyebrow">НАЧНИ СО ЗНАКОМСТВА</span><h2>Посмотри, как это работает</h2><p>${v.title}. Можно смотреть видео или сразу читать — как тебе удобнее.</p>${kBtn('Смотреть видео','video')}</div></section><div class="k-lesson-options"><button data-k-mode="read">${kAsset('course')}<span><strong>Разобраться в теме</strong><small>Цельное объяснение и живые примеры</small></span>${clarityIcon('arrow')}</button><button data-k="lesson-practice">${kAsset('training')}<span><strong>Попробовать самому</strong><small>3 задания · подсказки рядом</small></span>${clarityIcon('arrow')}</button></div>`}
function kRecommendations(){const mapped={1:'fractions',3:'equations',5:'chance'};return radarAreas.map((a,i)=>({...a,index:i,id:mapped[i],score:radarValue(a,'current')})).filter(a=>a.id&&a.score<80).sort((a,b)=>a.score-b.score)}
function kTraining(){if(kReady)return kPreparation();const errors=kErrors();return `<header class="k-page-heading"><span class="k-eyebrow">СПОКОЙНО РАЗБЕРЁМСЯ</span><h1>С каждым разом понятнее.</h1><p>Вернись к сложному. Или укрепи то, чему нужно немного внимания.</p></header>${kSession?`<div class="k-resume"><span>Ты остановился в «${kSession.title}».<br><strong>Задание ${kSession.position+1} из ${kSession.keys.length}</strong></span>${kBtn('Продолжить','resume')}</div>`:''}<section class="k-error-card">${kAsset('training')}<div><span class="k-eyebrow">РАБОТА НАД ОШИБКАМИ</span><h2>${errors.length?'Есть что разобрать':'Ошибок пока нет'}</h2><p>${errors.length?`Для повторения: ${errors.length} ${kPlural(errors.length)}. Разберём их без спешки.`:'Здесь появятся задания, которые не получились. После верного ответа они уйдут из списка.'}</p>${errors.length?kBtn('Посмотреть задания','review-errors'):`<button class="k-text-button" data-k-nav="today">Перейти к урокам ${clarityIcon('arrow')}</button>`}</div></section>${errors.length?`<div class="k-error-list">${errors.map(key=>`<button data-k-error="${key}"><span><small>${kTitle(key.split(':')[0])}</small><strong>${kGet(key).title}</strong></span>${clarityIcon('arrow')}</button>`).join('')}</div>`:''}<div class="k-section-heading"><div><span class="k-eyebrow">ПО КАРТЕ ЗНАНИЙ</span><h2>Вот что можно укрепить</h2></div><button class="k-text-button" data-k-nav="progress">К результатам ${clarityIcon('arrow')}</button></div><p class="k-recommend-note">Рекомендации по результатам теста: выбираем навыки ниже 80%. Сейчас показан пример работы от 2 октября.</p><div class="k-recommendations">${kRecommendations().map(a=>`<button class="k-recommendation" data-k-skill="${a.id}"><div class="k-score" style="--score:${a.score}%"><span>${a.score}%</span></div><span><strong>${a.label}</strong><small>${a.current} из ${a.total} верно в тесте</small><em>Повторить основу · 3 задания</em></span>${clarityIcon('arrow')}</button>`).join('')}</div>`}
function kPreparation(){return `<button class="k-text-button" data-k="training-back">${clarityIcon('back')} К тренировкам</button><section class="k-preparation">${kAsset('training')}<span class="k-eyebrow">СНАЧАЛА ОСМОТРИМСЯ</span><h1>${kReady.title}</h1><p>${kReady.reason}</p><div class="k-prep-facts"><span><strong>${kReady.keys.length}</strong> ${kPlural(kReady.keys.length)}</span><span>Без таймера</span><span>С подсказками</span></div><ol>${kReady.keys.map(key=>`<li>${kGet(key).title}</li>`).join('')}</ol><p class="k-prep-note">После ответа покажем объяснение. Ошибаться можно.</p>${kBtn('Начать тренировку','start-ready')}${kReady.topic!==undefined?`<button class="k-text-button" data-k-topic="${kReady.topic}">Сначала посмотреть урок</button>`:''}</section>`}
function kPrepare(keys,title,reason,topic){kReady={keys:[...keys],title,reason,topic};go('training')}
function kStart(keys,title,returnTo='training'){kSession={keys:[...keys],title,position:0,correct:0,answered:0,returnTo};kReady=null;kSummary=null;choice=null;checked=false;hinted=false;go('practice')}
function kExercise(){if(!kSession)return `<section class="k-preparation">${kAsset('training')}<h1>Выбери, что повторим</h1><p>Начнём с ошибок или темы по карте знаний.</p>${kBtn('К тренировкам','training-back')}</section>`;const q=kQuestion(),right=choice===q.correct;return `<section class="k-exercise"><div class="k-session-progress"><span>${kSession.title}</span><strong>${kSession.position+1} / ${kSession.keys.length}</strong><div class="k-meter"><i style="width:${kSession.answered/kSession.keys.length*100}%"></i></div></div><h1>${q.title}</h1>${q.formula?`<div class="k-equation">${frac(q.formula)} ${q.equation?' = '+frac(q.equation):''}</div>`:''}<div class="j-answer-list" role="group" aria-label="Варианты ответа">${q.answers.map((a,i)=>`<button class="j-answer ${choice===i?'selected':''} ${checked&&i===q.correct?'correct':''} ${checked&&choice===i&&!right?'wrong':''}" data-k-choice="${i}" aria-label="${Array.isArray(a)?a.join('/'):a}${checked&&i===q.correct?', верный ответ':''}" aria-pressed="${choice===i}" ${checked?'disabled':''}><small>${i+1}</small><span>${frac(a)}</span></button>`).join('')}</div>${hinted&&!checked?`<aside class="k-hint" role="status"><strong>Давай по шагам</strong><p>${q.hint}</p></aside>`:''}<div class="k-answer-footer ${checked?right?'good':'bad':''}"><div>${checked?`<div class="k-feedback" role="status"><h2>${right?'Получилось!':'Давай разберёмся'}</h2><p>${q.explanation}</p></div>${kBtn(kSession.position===kSession.keys.length-1?'Завершить':'Дальше','next')}`:`${kBtn('Подсказка','hint',true)}<button class="k-button" data-k="check" ${choice===null?'disabled':''}>Проверить</button>`}</div></div></section>`}
function kProgress(){const xp=kXP(),correct=Object.values(kHistory).filter(v=>v.correct).length;return `${kSummary?`<section class="k-session-summary">${kAsset('progress')}<div><span class="k-eyebrow">ТРЕНИРОВКА ЗАВЕРШЕНА</span><h1>Ещё немного увереннее.</h1><p>${kSummary.correct} из ${kSummary.total} верно в этой попытке.</p></div></section>`:`<header class="k-page-heading"><span class="k-eyebrow">ТВОЯ КАРТА ОТКРЫТИЙ</span><h1>Посмотри, как ты растёшь.</h1><p>Здесь видно, что получается и что можно повторить.</p></header>`}<div class="k-progress-stats"><div><strong>${xp}</strong><span>очков опыта</span></div><div><strong>${correct}</strong><span>${kPlural(correct)} решено</span></div><div><strong>${kErrors().length}</strong><span>можно повторить</span></div></div><button class="k-progress-cta" data-k-nav="training">${kAsset('training')}<span><strong>${kErrors().length?'Разберём то, что не получилось':'Подберём следующий шаг'}</strong><small>Ошибки и рекомендации по тесту</small></span>${clarityIcon('arrow')}</button>${clarityRadar()}<p class="k-footnote">Карта показывает отдельную работу учителя. Тренировки не меняют результат теста.</p>`}
function kPage(){return ({today:kCourse,learn:kCourse,training:kTraining,lesson:kLesson,practice:kExercise,progress:kProgress,profile:kCourse})[screen]()}
// Capture only K controls before the legacy prototype handlers can start a task.
document.addEventListener('click',e=>{if(variant!=='k')return;const b=e.target.closest('button');if(!b||b.disabled)return;let handled=true;
if(b.dataset.kNav){if(b.dataset.kNav==='training')kReady=null;go(b.dataset.kNav)}
else if(b.dataset.kGrade){kGrade=Number(b.dataset.kGrade);kSave();render(false);document.querySelector('[data-k-grade="'+kGrade+'"]')?.focus({preventScroll:true})}
else if(b.dataset.kTopic!==undefined)kOpenLesson(Number(b.dataset.kTopic));
else if(b.dataset.kMode){kMode=b.dataset.kMode;render();window.scrollTo(0,0)}
else if(b.dataset.kSkill){const id=b.dataset.kSkill,a=kRecommendations().find(a=>a.id===id);kPrepare(kKeys(id),kTitle(id),`В тесте ${a.current} из ${a.total} верно. Повторим основу и попробуем три похожих задания.`,id==='fractions'?0:undefined)}
else if(b.dataset.kError){kPrepare([b.dataset.kError],'Разберём одно задание','Это задание раньше не получилось. Попробуем ещё раз.')}
else if(b.dataset.kChoice!==undefined){choice=Number(b.dataset.kChoice);render(false);document.querySelector('[data-k-choice="'+choice+'"]')?.focus({preventScroll:true})}
else {const action=b.dataset.k||(b.dataset.action==='clarity-start-practice'?'lesson-practice':null);switch(action){
case 'grade-five':kGrade=5;kSave();go('today');break;
case 'video':case 'read':kMode=action;render();window.scrollTo(0,0);break;
case 'lesson-practice':if(kMode==='read'){kRead[kTopics[topicIndex].id]=true;kSave()}kPrepare(kKeys(kTopics[topicIndex].id),kTopics[topicIndex].short,'Три задания по уроку. Можно вернуться к видео или объяснению в любой момент.',topicIndex);break;
case 'review-errors':kPrepare(kErrors(),'Работа над ошибками','Только задания, которые раньше не получились. Верные ответы уберут их из списка.');break;
case 'start-ready':if(kReady)kStart(kReady.keys,kReady.title);break;
case 'resume':go('practice');break;
case 'training-back':kReady=null;go('training');break;
case 'exit':if(screen==='practice')go('training');else go('today');break;
case 'hint':hinted=true;render(false);break;
case 'check':if(!kSession||choice===null||checked)break;checked=true;{const key=kSession.keys[kSession.position],correct=choice===kQuestion().correct;kHistory[key]={choice,correct,earned:correct||kHistory[key]?.earned===true};kSession.answered++;if(correct)kSession.correct++;kSave()}render(false);document.querySelector('[data-k="next"]')?.focus({preventScroll:true});break;
case 'next':if(!kSession||!checked)break;if(kSession.position+1===kSession.keys.length){kSummary={correct:kSession.correct,total:kSession.keys.length};kSession=null;go('progress')}else{kSession.position++;choice=null;checked=false;hinted=false;go('practice')}break;
default:handled=false;
}}
if(handled){if(clarityAudio.effects&&clarityAudio.context?.state==='running'){const now=clarityAudio.context.currentTime;const correct=b.dataset.k==='check'&&checked&&choice===kQuestion().correct;[...(correct?[523.25,659.25,783.99]:[587.33])].forEach((f,i)=>clarityTone(f,now+i*.1,.16,.09))}e.preventDefault();e.stopImmediatePropagation()}
},true);
